// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEspaco.Models;

#nullable disable

namespace SistemaEspaco.Migrations
{
    [DbContext(typeof(ProjetoEspacoContext))]
    partial class ProjetoEspacoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEspaco.Models.Espaco", b =>
                {
                    b.Property<int>("IdEspaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspaco"));

                    b.Property<int?>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEspaco")
                        .HasName("PK__Espaco__1EDE22F2CFB9AFFA");

                    b.ToTable("Espaco", (string)null);
                });

            modelBuilder.Entity("SistemaEspaco.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdEspaco")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pendente");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__0E49C69D01877F98");

                    b.HasIndex("IdEspaco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("SistemaEspaco.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF979A7A72BD");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaEspaco.Models.ViewModels.DashboardReserva", b =>
                {
                    b.Property<int>("TotalReservas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TotalReservas"));

                    b.Property<int>("ReservasAtivas")
                        .HasColumnType("int");

                    b.Property<int>("ReservasFinalizadas")
                        .HasColumnType("int");

                    b.HasKey("TotalReservas");

                    b.ToTable("DashboardReservaViewModel");
                });

            modelBuilder.Entity("SistemaEspaco.Models.Reserva", b =>
                {
                    b.HasOne("SistemaEspaco.Models.Espaco", "IdEspacoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEspaco")
                        .HasConstraintName("FK__Reserva__IdEspac__4F7CD00D");

                    b.HasOne("SistemaEspaco.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Reserva__IdUsuar__4E88ABD4");

                    b.Navigation("IdEspacoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaEspaco.Models.Espaco", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SistemaEspaco.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
